version: "3.8"
services:
    mysqldb:
        restart: always
        image: mysql:latest
        networks:
            - backend
        ports:
            - $MYSQLDB_PORT:$MYSQLDB_PORT
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
            - MYSQL_USER=$MYSQLDB_USER
            - MYSQL_PASS=$MYSQLDB_PASS
        volumes:
            - ./db:/docker-entrypoint-initdb.d
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: workana-challenge-api
        networks:
            - backend
        ports:
            - $APP_PORT:$APP_PORT
        depends_on:
            - mysqldb
        links:
            - mysqldb
        stdin_open: true
        tty: true
networks:
    backend: